name: "pactflow"

on:
  push:
    branches-ignore:
      - "master"

  pull_request:
    types:
      - "closed"

env:
  PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  PACTFILES: ./src/pact/pactfiles
  APPLICATION_NAME: "pact-demo-client2"
  ENVIRONMENT: test
  # In an ideal world this would be dynamic, maybe commit sha.
  VERSION: 1.1.0
  BRACH: $GITHUB_REF_NAME

jobs:
  test-release:
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/workflows/publish.sh
      - if: success()
        run: ./.github/workflows/can-i-deploy.sh

  deploy-pact-file:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/workflows/deploy.sh
